### ISSUE TITLE
Data Browser UI is getting distorted

### ISSUE THREAD

**Issue by CTDisasterManagement** [Esri/impact-summary-map-template-js#103]
@driskull 
Data browser UI is getting distorted after changing the below CSS links- http://js.arcgis.com/3.10/js/dojo/dijit/themes/claro/claro.css  to http://js.arcgis.com/3.13/js/dojo/dijit/themes/claro/claro.css 
and
http://js.arcgis.com/3.10/js/esri/css/esri.css to http://js.arcgis.com/3.13/js/esri/css/esri.css

Thanks!

**Comment by CTDisasterManagement** [comment]
Here is the screenshot of the distorted UI
![databrowser](https://cloud.githubusercontent.com/assets/5261405/6396569/2c2327da-be05-11e4-910b-c489d8f55835.PNG)

Thanks!

**Comment by driskull** [comment]
@CTDisasterManagement can you test and make sure its working correctly now.

**Comment by CTDisasterManagement** [comment]
@driskull We tested and its working fine now.
