### ISSUE TITLE
Validation for buffer distance in geoenrichment

### ISSUE THREAD

**Issue by CTDisasterManagement** [Esri/impact-summary-map-template-js#78]
@pjdohertygis 

Just wanted to confirm the maximum buffer distance the user can enter.

![image](https://cloud.githubusercontent.com/assets/5261405/4996417/75e85654-69ed-11e4-8cdc-ff55364019cb.png)

Thanks!

**Comment by driskull** [comment]
@DerrickBurke assigning to you. Not sure what it should be.

**Comment by DerrickBurke** [comment]
@driskull here's some guidance from Ash (we should not allow over these max values):


The enrichment service does have limits.  They are listed here:
http://wildcard:6080/arcgis/rest/services/World/geoenrichmentserver/Geoenrichment/ServiceLimits

**Comment by driskull** [comment]
paramName: MaximumAttributeDescriptionLength
paramDescription: Maximum length of attribute’s description string.
dataType: numeric
value: 10000

paramName: MaximumDataCollections
paramDescription: Maximum number of data collections to return on request.
dataType: numeric
value: 1000

paramName: MaximumDrivetimeStudyAreasNumber
paramDescription: Maximum number of study areas in one enrich request.
dataType: numeric
value: 10000

paramName: MaximumOutFieldsNumber
paramDescription: Maximum number of ‘outFields’ set in the intersectingGeographies parameter.
dataType: numeric
value: 2560

paramName: MaximumRingSize
paramDescription: Maximum ring size for the drive time/simple rings builder.
dataType: esriMiles
value: 10000

paramName: MaximumRingSizeTime
paramDescription: Maximum ring size in time units for the drive time rings builder.
dataType: esriDriveTimeUnitsMinutes
value: 300

paramName: MaximumRingsNumber
paramDescription: Maximum number of rings for the study area location points for the drive time/simple rings builder.
dataType: numeric
value: 10000

paramName: MaximumStdGeographyIDsNumber
paramDescription: Maximum number of standard geography IDs to return.
dataType: numeric
value: 50000

paramName: MaximumStudyAreasNumber
paramDescription: Maximum number of study areas in one enrich request.
dataType: numeric
value: 10000

**Comment by driskull** [comment]
not sure if this is the same thing as we need to know

**Comment by DerrickBurke** [comment]
let's send to Ash the specific enrichment areas we are looking for

e.g. line distance max values for (kilometers, miles, feet, yards etc)
e.g. drive time max values for (miles, kilometers etc)

@driskull can you post these and I can chase down with Ash?

**Comment by driskull** [comment]
We just need the min/max/default line buffer distance for enriching a layer. Like shown in the screenshot above. cc @DerrickBurke

**Comment by DerrickBurke** [comment]
ok any specific units? @driskull

**Comment by driskull** [comment]
Just meters I think. We could convert between them if necessary.

**Comment by DerrickBurke** [comment]
@driskull from Ash

I believe it is:
paramName: MaximumRingSize
paramDescription: Maximum ring size for the drive time/simple rings builder.
dataType: esriMiles
value: 10000
 
Which would be 16,093,440 meters.

**Comment by driskull** [comment]
Thanks! @CTDisasterManagement lets check for these maximums.

**Comment by CTDisasterManagement** [comment]
@driskull,

We have added validation for “Line Distance” but but what maximum hours we have to set incase of “Driving Time”.
![drive_time_maxhours](https://cloud.githubusercontent.com/assets/5261405/6045333/5e002b06-acbf-11e4-870e-c51dc892a1da.PNG)

Thanks!

**Comment by driskull** [comment]
@CTDisasterManagement I have no clue. Lets just limit it to 10 for now. @DerrickBurke do you have any suggestions?
