### ISSUE TITLE
Accessing sharing properties of layer

### ISSUE THREAD

**Issue by CTDisasterManagement** [Esri/impact-summary-map-template-js#84]
@driskull,

We can get the access properties of layer only if it has item id.
If layer without item id is selected for enrichment process, we cannot get the access properties and therefor we cannot grant the access properties for newly created layer. 

Can you please let us know how to proceed in this case?
Thanks!

**Comment by CTDisasterManagement** [comment]
@driskull 

Once a layer is created from geoenrichment process, it will be added as item in user portal.But when we add the same in our web map it will be added as a layer.
So,we will never get item id and hence we cannot share the layer.

Solution:
1) We  can show popup for share layer as soon as we get enriched layer and give user privilege to share the layer with public and specific group.

2) Once a newly enriched layer is added to web map then on click of "Next" button we will show the sharing options in new dialog and when user clicks on "save" we will save the settings and reload the application.

We are planning to create dialog similar to this one:
![share](https://cloud.githubusercontent.com/assets/5261405/5701693/098d99ac-9a75-11e4-9685-d34a46fe2f98.PNG)

Please let us know your feedback.

Thanks!

**Comment by driskull** [comment]
@CTDisasterManagement can't we share the layer after we create the layer item? That's how i'm doing it with this app:

https://github.com/driskull/the-geoenrichinator-js/blob/master/js/main.js#L111

We should be sharing it before we add it to the map I think.

See the code above.

**Comment by driskull** [comment]
@CTDisasterManagement can you share the status of this issue?

Thanks

**Comment by CTDisasterManagement** [comment]
@driskull 

This issue has been fixed.We are testing and fixing some minor issues and will send the pull request tomorrow.

Thanks!

**Comment by driskull** [comment]
awesome. thanks
