### ISSUE TITLE
Option for geometries to be fully selected

### ISSUE THREAD

**Issue by driskull** [Esri/impact-summary-map-template-js#85]
-Reference info below:

![ce51e03d-ba65-4aa3-bf25-3289af9104d6](https://cloud.githubusercontent.com/assets/1231455/5635018/2260da46-959a-11e4-9654-fbcbdd9a07b2.png)

All,
I am working with the Public Impact template and wondered if we could make a simple change to help with clarity. I had someone ask me this at GEMA during their winter exercise. The selection areas for the impact map are a bit unclear since they highlight the borders of features, not the entire feature itself. This is an issue with nested polygons like this Drought Monitor Impact Map I made:
<CE51E03D-BA65-4AA3-BF25-3289AF9104D6.png>

The area in question is not selected, just the polygon surrounding it. Could we change the selection to fill in the entire polygon, not just the boundary?
Here is the link to the Impact Map I am putting together. http://seem.maps.arcgis.com/apps/ImpactSummary/index.html?appid=a10af668139146ef9cb6e8c3397caace&webmap=08f1bae331664ff0b5329becebc3c765

Thanks

**Comment by driskull** [comment]
cc @pjdohertygis

**Comment by CTDisasterManagement** [comment]
@driskull, @pjdohertygis 

To resolve the above use case we can give different options to highlight selected impact area.

We can add more options in "Selected Feature" dropdown such as:
STYLE_DIAGONAL_CROSS(Diagonal Cross)
STYLE_FORWARD_DIAGONAL(Diagonal Forward)
STYLE_SOLID,STYLE_VERTICAL(Diagonal Vertical)
![image](https://cloud.githubusercontent.com/assets/5261405/5741872/2b076020-9c34-11e4-9e66-e92e40e3c43d.png)

Will this work? Or you want anything else?

Thanks!

**Comment by driskull** [comment]
yeah that will work.

**Comment by CTDisasterManagement** [comment]
@driskull 

We saw the API change in index.html  but with 3.13 ArcGIS API "Select Feature" Functionality from renderer panel is not working as expected.But when we change the API to 3.12 it works fine.

Thanks!

**Comment by driskull** [comment]
Yes, I can help investigate what's going on. we need to use 3.13 because that will be the version released in end of Feb. Please send me a link to test and I will investigate.

**Comment by CTDisasterManagement** [comment]
@driskull 

Here are our finding on this issue:
With 3.12 API when we query "aoiLayer" with "queryFeatures"().Output contains all the required information with symbols. 
But with 3.13 API, if we use "queryFeatures", output contains desired information but symbol is undefined and this is the reason we are not able to style the symbol.
![queryfeature](https://cloud.githubusercontent.com/assets/5261405/6127050/a453385a-b14c-11e4-9d33-42f2aaaa4449.PNG)

However, if we use "SelectFeature" with 3.12 and 3.13 API, query returns all the information with symbol and functionality works as expected.
![selectfeature](https://cloud.githubusercontent.com/assets/5261405/6127116/72bc3944-b14d-11e4-8586-8573f4995af0.PNG)

Thanks!

**Comment by driskull** [comment]
Ok, lets use selectFeatures then.

**Comment by CTDisasterManagement** [comment]
@driskull,

We have replaced "queryFeatures" with "selectFeatures" and we are testing the functionality with different web maps.
We will send the pull request tomorrow.

Thanks!

**Comment by driskull** [comment]
thanks!

**Comment by driskull** [comment]
Code needs to be JSHint. I merged it in though.

**Comment by driskull** [comment]
@CTDisasterManagement can you JSHint all the JS to make sure there are no issues with compatibility or future code.

**Comment by CTDisasterManagement** [comment]
Sure @driskull 

We will JSHint all the js files and send new pull request soon.

Thanks!

**Comment by driskull** [comment]
Thanks looks good.
