### ISSUE TITLE
Legend of the left is not updated or changed once the scale of the map is updated.

### ISSUE THREAD

**Issue by GeoGeeks** [Esri/impact-summary-map-template-js#86]
We have implemented this template to display the count of the number of infected by a virus in Colombia, the site map has two layers, which are configured to be displayed depending on the map scale, component Legend is working properly, then when the user zoom in, the component, turn off the legend of the most general layer and shows the new layer, but when the user zoom in the legend on the left is not updated, to allow the user to see the new color ranges and values, functionality keep for the most general layer.

Here I give a link to the implementation of the template, so that the issues is reproduce.

http://industry-esri-co.maps.arcgis.com/apps/ImpactSummary/index.html?appid=1b53abe51d764457bc27d0107374ebc6&webmap=42402e75ecd0465ea42637c32acd5312

**Comment by driskull** [comment]
Hey @GeoGeeks, The template will only work with one layer that can be used to display data. We could add functionality to have the nav legend update or not show depending on the renderer at that scale but we can't switch layers at a specific scale. Is that what you're looking for?
