### ISSUE TITLE
Disable enrichment option if the template is being used in a portal

### ISSUE THREAD

**Issue by driskull** [Esri/impact-summary-map-template-js#87]
If the template is configured using a portal that may be offline or not have access to enrichment services, we should not show the enrichment steps.

--------------

That’s a good point. I’ll log a github issue to disable enrichment if in portal mode.

Matt Driscoll | Web Developer
Esri | 380 New York Street | Redlands, CA 92373 | USA
T 909 793 2853 x3587 | mdriscoll@esri.com | esri.com

From: Ian Wittenmyer <iwittenmyer@esri.com>
Date: Thursday, January 15, 2015 at 3:53 PM
To: Molly Zurn <mzurn@esri.com>, Kim Peter <kpeter@esri.com>, Matt Driscoll <mdriscoll@esri.com>
Subject: RE: Impact Summary

This template can be used to sum numerical data and doesn’t require output from the tools mentioned in order to work.  The key piece of info is that it ‘can be any integer data…’. I think its ok to leave the second paragraph as is since it just says ‘For instance…’
 
In the 3.7 update, it will support Enrichment from within the application builder.
 
Matt,
 
Will you be checking the self-call for isPortal true and disabling this functionality?
 
From: Molly Zurn 
Sent: Thursday, January 15, 2015 3:03 PM
To: Kim Peter; Ian Wittenmyer
Subject: RE: Impact Summary
 
“ArcGIS Online web map” isn’t really a meaningful term, especially now that Pro creates web maps.
A web map is a web map is a web map…..
 
Do you mean the map viewer?
 
From: Kim Peter 
Sent: Thursday, January 15, 2015 2:50 PM
To: Ian Wittenmyer
Cc: Molly Zurn
Subject: Impact Summary
 
The item details for Impact Summary mention using analysis tools that are only available in Online, right?  Maybe this is one place where the item details should call out using it with Online. (i.e., “For instance, in an ArcGIS Online web map, you could enrich your polygon demographics, landscape, infrastructure…”)

**Comment by CTDisasterManagement** [comment]
@driskull 

We are fetching GPServer enrichment process url from portal info.
![portaluser](https://cloud.githubusercontent.com/assets/5261405/5777762/85f3c220-9dbb-11e4-9e6d-b49f1c399df5.jpg)

So we can disable the enrichment process if this information is not available in portal.
Need you inputs on this.

Thanks!

**Comment by driskull** [comment]
Yep. that sounds good.

**Comment by CTDisasterManagement** [comment]
@driskull 

For ArcGIS trial accounts we are able to perform the analysis(Geo enrichment) but in users portal information we are not able to get the 'Analysis url'.
So user can perform the enrichment process in ArcGIS but not in our application.
We are investigating on this and will keep you updated. 
Thanks!

**Comment by driskull** [comment]
Ok, keep me posted. thanks
