### ISSUE TITLE
Basemap Toggle - does not let you switch back to default basemap

### ISSUE THREAD

**Issue by pjdohertygis** [Esri/impact-summary-map-template-js#89]
I am not sure who configured this one, but when I open it as an end user, if I click on the basemap toggle it successfully takes me to the imagery hybrid, but then fails to take me back to Dark Gray basemap which was the default. We should make this easier for Users to configure so that the default always matches the one they choose in the web map. 

http://disasterresponse.maps.arcgis.com/apps/ImpactSummary/index.html?appid=0310fce4b53e42839cfd8309868ae93f&webmap=c77ef3ddd7c84a14b18528d98b9c3f32

**Comment by driskull** [comment]
that one seems to work for me. It's  a known API limitation that will not be fixed until 4.0.
