### ISSUE TITLE
Legend doesn't work in 3.13 API(Random Behavior)

### ISSUE THREAD

**Issue by CTDisasterManagement** [Esri/impact-summary-map-template-js#99]

**Comment by driskull** [comment]
@CTDisasterManagement can you provide an example so I can test?

**Comment by CTDisasterManagement** [comment]
@driskull 

This is random behavior.When we call the legend widget the code breaks.
Currently it is working, if it breaks we will send you the screenshot of the error in console.

**Comment by driskull** [comment]
Ok thanks. It may have been something that they already fixed so I'll see if they are aware of any issue with it. The 3.13 dev API gets rebuilt every night so it may have changed.

**Comment by CTDisasterManagement** [comment]
@driskull 

This is random behavior.When we call the legend widget the code breaks.
Currently it is working, if it breaks we will send you the screenshot of the error in console.

**Comment by CTDisasterManagement** [comment]
Thanks @driskull

**Comment by driskull** [comment]
@CTDisasterManagement Let us know if you find a reproducible case.
